# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherForcast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherForcast
  pod 'Alamofire', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'
end
