# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalStock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalStock
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod “SwiftSpinner"
end
